version: "3.8"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=`${POSTGRESS_PASSWORD}`
    networks:
      - internal
    restart: always

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - internal
    restart: always

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    env_file:
      - .env  
    networks:
      - internal
      - traefik
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.plausible.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.plausible.entrypoints=websecure
      - traefik.http.services.plausible.loadbalancer.server.port=8000
      - traefik.http.routers.plausible.tls.certresolver=${CERT_RESOLVER}

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  traefik:
    name: traefik
  internal:
    external: false
